### PR TITLE
Add number and email fields

### PR DESCRIPTION
**Pull request by zevilz**
Number field supports max (max_value/set_max_value methods), min (min_value/set_min_value methods) and step (step/set_step methods) attributes.

### CODE REVIEW

**Comment by atanas-angelov-dev** [comment]
Thank you for the contribution @zevilz , however I will have to close this pull request as we no longer accept pull requests for features aimed at 1.x releases.

Note that Number field is already done and will be released as a separate package together with 2.0 and the base Text field will allow you to change a number of its input's attributes (e.g. type, pattern, placeholder etc.)

**Comment by zevilz** [comment]
And where can i get 2.0?

**Comment by zevilz** [comment]
I'm find it)

**Comment by atanas-angelov-dev** [comment]
2.0 is in beta but will have an official release very soon.

**Comment by dmhendricks** [comment]
I love CF in almost every way - I use it on SO many client projects every day! The Text field is embarrassing. I forked it and tried to improve. Denied pull request. I'm not butt hurt about that, but it is really weird that we have to hack around such an essential element.... {wait for element to render} ... {do some jQuery magic to make it do what you kind of want it to do} ... {FOUC #fail}

I am **happy** to contribute (I am not _nearly_ as skilled as the primary contributors; I reluctantly admit that I have been wrong in the past), but it seems that Text_Field is as good as it gets.

I still give significant love because CF is pretty excellent (It has saved me a **lot** of dev time; I wish that it was targeted as a framework rather than a plugin, but whatev; I have encountered some legacy issues when using Composer; I am grateful for PSR-4).

That all said, the Text field is pretty terrible, yeah? A plugin's API key should not have to be clear text without involving a nightmare... etc, etc... [#placeholder](https://www.w3schools.com/tags/att_input_placeholder.asp) [#password](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_password) [#selectors](https://www.w3schools.com/cssref/css_selectors.asp) [#fieldtypes](https://html5tutorial.info/html5-contact.php)

I am bitching, but I am very grateful for all who have contributed to a great plugin. As mentioned, y'all have saved me a lot of time, and time is money.

I have researched a LOT of "frameworks," and Titan is probably the next best (SASS!)... But, I still prefer CF. So much potential and so close to being perfect.

**Comment by atanas-angelov-dev** [comment]
Thank you for your feedback @dmhendricks ,

I believe this is all covered in your #267 ticket so I've answered there.

**Pull request closed without merging**
