### PR TITLE
The method set_attribute () was edited

### PR DESCRIPTION
**Pull request by campusboy87**
Added support for an array in the set_attribute () method

### CODE REVIEW

**Comment by atanas-angelov-dev** [comment]
Thank you for the contribution @campusboy87 but I feel a few changes should be made before we can accept the pull:

1. Instead of making the `set_attribute()` function multi-purpose, add a separate `set_attributes( $attributes )` method that accepts only a single key=>value dictionary.
2. The new method should call `$this->set_attribute( $key, $value )` to avoid duplication and nesting

Let me know if you are willing and have the time to make these changes or close the pull and submit a feature request ticket so we can address it when we can.

Thanks!

**Comment by campusboy87** [comment]
I will try to correct this moment. Thanks for the comments!

**Comment by atanas-angelov-dev** [comment]
Thanks @campusboy87 - your pull was merged 👍

**Comment by campusboy87** [comment]
Thank you for trust. I'm studying, therefore I am glad for any corrections on your part.

**Pull request merged**
