### PR TITLE
Add finnish translation

### PR DESCRIPTION
**Pull request by timiwahalahti**

### CODE REVIEW

**Comment by m1r0** [comment]
Thanks a lot @timiwahalahti!

**Comment by timiwahalahti** [comment]
Is there any plans to release new version on w.org plugin repository and include this translation in it? Or should I ask rights to translate CF directly in w.org in favor to get it shipped?

**Comment by timiwahalahti** [comment]
@m1r0 Can you ask adding me as Finnish translation editor at make.wordpress.org/translate [like this](https://make.wordpress.org/polyglots/2017/04/29/hello-polyglots-i-am-the-97/), so I can put this translation to w.org translation tool and getting it shipped?

**Comment by m1r0** [comment]
Timi, thanks for the interest in helping out with the translation. We are in the process of a major rewrite and localization is on hold for now. When things are final and the the next major release is out and we will focus on localization and definitely contact you about it. Stay tuned :-)

**Pull request merged**
