### PR TITLE
Update Finnish translation

### PR DESCRIPTION
**Pull request by timiwahalahti**
Somehow latest update(s) broke Finnish translation. Here's a new working version.

### CODE REVIEW

**Comment by atanas-angelov-dev** [comment]
Thank you for the contribution @timiwahalahti , however, it seems you are a few commits behind which have a couple new strings.

Could you please pull our development branch into your fork and update the language files again (you should see the new "Collapse All" and "Expand All" strings)?

**Comment by atanas-angelov-dev** [comment]
Any update on this? I won't be able to merge this pull request in it's current state.

**Comment by timiwahalahti** [comment]
Sorry I totally forgot this! Just updated language files against development branch.

**Comment by atanas-angelov-dev** [comment]
Thank you for the contribution @timiwahalahti !

**Pull request merged**
