### PR TITLE
Feature/multiselect field

### PR DESCRIPTION
**Pull request by ppetrov2create**
This request adds a multiselect field.
The Set field was used as base.
Using [react-select](https://github.com/JedWatson/react-select).

### CODE REVIEW

**Comment by atanas-angelov-dev** [comment]
Changes needed:
- Remove `limit_options` - it only makes sense in Set field context
- Remove `parse_options` method definition - it is already inherited from `Predefined_Options_Field`
- Test in Widget and Nav_Menu containers, inside and outside of a complex field (`field_name + '[]'` may cause problems)
- Test if any of these options are not properly saved or marked as selected after saving:
    ```php
    ->add_options( [
        'foo' => 'Foo',
        0 => '0'
        1 => 1
        'bar' => 'Bar',
    ] )
    ```

**Comment by AMO-MGTSYS** [comment]
Hi All and thank you for this great library.
I have a use case where this feature will help me avoid using a repeated field and some parsing.
Have you a target date for merging this? (just asking :) )

**Comment by atanas-angelov-dev** [comment]
@AMO-MGTSYS 

There are minor issues to be resolve so it's just a matter of when we will find the time to finalize this.
Note that the `'set'` field type can be a potential solution in the meantime depending on your use case.

**Comment by AMO-MGTSYS** [comment]
Thank you @atanas-angelov-dev . 
Set is great, i have a 20 options to display but i can use limit_options( $count ).

**Pull request merged**
