### PR TITLE
Add missing localization for complex field no entries message

### LINKED ISSUE #790: The "There are no entries yet." text that appears in complex fields when there's still no entries added is not translatable.
## Version

  - Carbon Fields: 3.1.8
  - WordPress: 5.3
  - PHP: 7.2

## Expected Behavior
The string is translatable

## Actual Behavior
The string is not translatable

## Steps to Reproduce the Problem

  1. Create a complex field.
  1. See how the "There are no entries yet." text is not translatable

## Comments
The "There are no entries yet." text that appears in complex fields when there's still no entries added is not translatable.

### PR DESCRIPTION
**Pull request by lstoyanoff**
Fix #790

### CODE REVIEW

**Comment by muzanaka** [comment]
It's awesome? that you repair it, but there is no information how to translate this text

**Comment by emohamed** [comment]
@muzanaka check here: https://github.com/htmlburger/carbon-fields/pull/823/files -- the string is `There are no entries yet.`

**Comment by muzanaka** [comment]
@emohamed  Field::make( 'complex', 'expects', 'Ожидания')->set_layout( 'grid' )->set_WHAT('translate_this_string')

**Comment by lstoyanoff** [comment]
Hi @muzanaka,
You should either manually generate `.po` and `.mo` files from the Carbon Fields `.pot` using a translation tool like for example [poedit](http://www.poedit.net/) or install a WordPress plugin for managing string translations ( I would recommend using [Loco Translate](https://wordpress.org/plugins/loco-translate/) ) which will automatically find all `.pot` files in your WordPress theme/plugins.

You can find more information about localization in the WordPress Docs -- https://developer.wordpress.org/apis/handbook/internationalization/localization/

**Pull request merged**
