### PR TITLE
Coding standards for Carbon Fields:

### PR DESCRIPTION
**Pull request by nlemoine**
- Add WordPress Coding Standards to composer.son to require-dev
- Remove autoload files from composer.json (causes phpcs errors)
- Fix coding standards for PHP files

### CODE REVIEW

**Comment by tyxla** [comment]
Hey @nlemoine,

Thanks for the PR! Looks good at first glance, I can see several things that have to be looked at:

1. The `phpcs` configuration listed in `composer.json` does not work on Windows for some reason.
2. Scrutinizer inspection fails. Probably because of the empty `require`?
3. Lets not include `phpcs` as a dependency at this time. Instead, you can try setting it up at the Scrutinizer config, as shown here: https://github.com/scrutinizer-ci/scrutinizer/pull/66 . This will also fix `1.`, as these config lines will be removed.
4. Removing `files` from `autoload` makes sense in terms of conforming standards, but it would cause some functionality to be missing. Lets leave it for now until we find a better solution.

Please, let me know if you need additional information.

**Comment by nlemoine** [comment]
1. That's a shame. Did you try babun? http://babun.github.io/
2. I saw that and did not really understand why. `composer validate` returns ok. You're right, the empty require caused the issue. 
3. I tried this Scrutinizer feature and I don't see any checks on WordPress coding standards. If you run `phpcs --standard=WordPress-Core core/`, you'll see many errors are not reported. 
Besides, the plugin is not passing Coding Standards checks yet. In a first time, I think you may exclude coding standards checks from CI, adjust the ruleset to your needs (this your project, I don't want to enforce some coding standards and sometimes, WordPress rules don't fit) and when everything is fixed/set, include custom coding standards checks (https://scrutinizer-ci.com/docs/tools/php/code-sniffer/)
4. As explained here : https://github.com/htmlburger/carbon-fields/issues/7#issuecomment-198303083, nothing will be missing, files inclusion is done twice (autoload + require_once).

Let me know if you need some other changes.

**Comment by tyxla** [comment]
Good points there, @nlemoine.

1. Yep. The issue was coming from the composer configuration, and has been fixed with your latest commit.
2. Yeah, that was weird indeed.
3. Makes sense. I've just tried various *easy* ways to get Scrutinizer working with the WordPress coding standards on-the-fly. It appears we'll have to list all the sniffs in order to check for them in Scrutinizer. Let's stay with manually calling `phpcs` for now. I've created an issue for that, we'll address it separately there: https://github.com/htmlburger/carbon-fields/issues/11
4. Yes, the files will be automatically loaded if Carbon Fields is installed as a plugin (this is when `carbon-fields-plugin.php` is used). However, if you're using it as a library, they wont be included, as `carbon-fields-plugin.php` is not used in that case. That's why it is best to keep the files there for now. In the future, we might move their `include` / `require` calls to one of the other files.

So, with https://github.com/htmlburger/carbon-fields/issues/11 open I believe we're good to go here. I'll perform a final check before merging. 

Thanks! :+1:

**Comment by nlemoine** [comment]
> I've just tried various easy ways to get Scrutinizer working with the WordPress coding standards on-the-fly.

I struggled a bit with their doc, it's not very intuitive but I'm not very familiar with Scrutinizer.

 > It appears we'll have to list all the sniffs in order to check for them in Scrutinizer.

IMHO, that's why I think it's more convenient to optin for a set of rules (say WordPress-Core for example) and exclude the ones you don't want.

I see another major con with storing the sniffs in the scrutinizer.yml file. They can't be used with PHP Code Sniffer on your local environment. This means you have to sync all sniffs from the yaml file to the xml ruleset file. 

Did you try the custom ruleset path? https://scrutinizer-ci.com/docs/tools/php/code-sniffer/
It could resolve both issues mentionned above. 

> One last thing: can you remove the scripts and require-dev from composer.json - they're not necessary for now.

I will in a minute!

**Comment by tyxla** [comment]
> IMHO, that's why I think it's more convenient to optin for a set of rules (say WordPress-Core for example) and exclude the ones you don't want.

Yeah, that's exactly how I'll proceed in https://github.com/htmlburger/carbon-fields/issues/11 once I get to it.

> I see another major con with storing the sniffs in the scrutinizer.yml file. They can't be used with PHP Code Sniffer on your local environment. This means you have to sync all sniffs from the yaml file to the xml ruleset file.

Agree, that's what I was thinking as well. In https://github.com/htmlburger/carbon-fields/issues/11 we'll work on defining a custom ruleset that will be used in Scrutinizer, but will also be usable in `phpcs` in local environments.

> Did you try the custom ruleset path? https://scrutinizer-ci.com/docs/tools/php/code-sniffer/ It could resolve both issues mentionned above.

Yes, it will work with a custom ruleset within the project, this will be addressed in https://github.com/htmlburger/carbon-fields/issues/11

> I will in a minute!

I can see that's done, thanks :+1: 

I think nothing else is necessary here, I'll do a final check tomorrow before merging.

**Comment by nlemoine** [comment]
:+1: Thanks for your feedback!

**Comment by tyxla** [comment]
Thanks for your contribution :shipit:

**Pull request merged**
