### PR TITLE
Update Scripts_Field.php

### PR DESCRIPTION
**Pull request by 9585999**
The output of user scripts with priority 100.

### CODE REVIEW

**Comment by atanas-angelov-dev** [comment]
Hello @9585999 and thank you for your contribution, however, can you let us know why this is needed and what problems does it solve?

**Comment by 9585999** [comment]
Hello @atanas-angelov-dev,  I started using CarbonFields only yesterday, and I liked this plugin, I noticed that it has integration with bedrock. I use bedrock and sage, in sage by default Theme Assets is connected with priority 100. I think it will be more logical if these fields are displayed after standard styles / scripts.

Since if you do not specify a priority of 100, in the DOM they are displayed above the theme files.

**Comment by atanas-angelov-dev** [comment]
I've actually went ahead and reworked the Scripts field to be more flexible instead of hardcoding the hook and priority:
https://github.com/htmlburger/carbon-fields/commit/a4aa3a96b5151a1e9e30b4cf4ad142c33090fd5f

**Comment by atanas-angelov-dev** [comment]
Thank you for the feedback!

I actually went ahead and reworked the Scripts field in a4aa3a96b5151a1e9e30b4cf4ad142c33090fd5f to be more flexible instead of hardcoding unchangeable hook and priority in.

Scripts fields how have `set_hook_name( $name )`, `set_hook_priority( $priority )` and `set_hook( $name, $priority )` methods.
This change will be available in the next patch release (2.0.4).

**Pull request closed without merging**
