### PR TITLE
Fix display tab on user_meta

### PR DESCRIPTION
**Pull request by elvishp2006**
captura de tela de 2016-12-08 14 24 30

### CODE REVIEW

**Comment by yuliyan** [comment]
It looks like you are using the old CSS - we did major rewrite in the several weeks and that is still not released in WordPress.org or in GIT tag.

Could you please provide us the definition of the container that you use here?

Additionally, could you please confirm that the problem exists in the latest version of carbon fields? You can update via: `composer require htmlburger/carbon-fields:dev-master`

**Comment by elvishp2006** [comment]
I am using this lib in a plugin, this command created a folder named "wp-content", when I used only the ```composer require htmlburger/carbon-fields``` command it was placed inside the vendor folder normally, which command should I use?

Follow the code I'm using:

```php
Container::make( 'user_meta', 'Endereço' )
	->add_fields(
		array(
			Field::make( 'text', 'city_and_post', 'Cidade e código postal' ),
			Field::make( 'text', 'street', 'Rua' ),
			Field::make( 'complex', 'professional_exp', 'Experiências profissionais' )
				->set_layout( 'tabbed-horizontal' )
				->add_fields(
					array(
						Field::make( 'text', 'company', 'Empresa' )
							->set_required( true ),
						Field::make( 'text', 'office', 'Cargo' )
							->set_required( true ),
						Field::make( 'textarea', 'activities', 'Atividades desempenhadas' )
							->set_required( true ),
					)
				)
				->set_header_template('
					<# if (company && office) { #>
						{{ company }}, {{ office }}
					<# } #>
				'),
		)
	);
```

**Comment by pkostadinov-2create** [comment]
This happened recently, when the composer type was changed to WordPress plugin. You need to modify your `composer.json`  manually and add the `extra` parameter, after which `composer update` will download in the vendor folder, as it did previously:

```
{
    "type": "project",
    "require": {
        "htmlburger/carbon-fields": "dev-master",
    },
    "extra": {
        "installer-paths": {
            "vendor/{$vendor}/{$name}/": ["type:wordpress-plugin"]
        }
    }
}
{
    "type": "project",
    "require": {
        "htmlburger/carbon-fields": "dev-master",
    },
    "extra": {
        "installer-paths": {
            "vendor/{$vendor}/{$name}/": ["type:wordpress-plugin"]
        }
    }
}
```

**Comment by elvishp2006** [comment]
Great, now it's working perfectly, thank you: D

**Pull request closed without merging**
