### PR TITLE
Possibility to provide id and label for containers

### PR DESCRIPTION
**Pull request by tschortsch**
Was there a specific reason why it wasn't possible to provide a label for a container (besides to the id)? The current solution doesn't allow to make container labels translatable because they have to be unique. 

In my solution it is possible the provide a `name` besides the `id` of the container. It should be fully backwards compatible since the additional parameter isn't required.

### CODE REVIEW

**Comment by tyxla** [comment]
This approach will totally break backwards compatibility, which we always avoid as much as possible.

**Comment by tschortsch** [comment]
Can you specify how exactly this will break backwards compatibility? I defined the new parameter as optional. If it's left empty the $id (first parameter) is copied inside the $title variable.

**Comment by tyxla** [comment]
Any plugin or theme that relies on this parameter order might break. We have several internal plugins that wrap around Carbon Fields and extend it. They rely on the exact parameter order and extend the default containers to add more parameters. 

So I think it would be a better option to add parameters at the end, not at the middle. This would solve the issue I'm describing, and would reduce the chance to break backward compatibility.

Also, might be confusing for users if the first parameter can be both id and title (depending on the parameter count). Lets avoid this for comprehensibility reasons, and keep the first parameter always the title, and introduce a new optional parameter for ID. Thoughts?

**Comment by tschortsch** [comment]
Ah I see. I could implement your solution. The only problem I see is that the order of the parameters then is different to the Field::factory() method which the $label comes after the $name (id).

**Comment by tyxla** [comment]
It sounds good to me. Some more opinions here would be helpful.

**Comment by EmilEriksen** [comment]
I'm not sure how this would break backwards compatibility. @tschortsch isn't changing the parameter order - he's just renaming what's currently $title/$name to $id which makes a lot more sense IMO.  I only had a quick glance though. It's a little confusing that $title/$name has two different variable names in different places. Any reason for this?

It is indeed confusing that the first parameter can be both the title and the id but tbh I think it was a poor design decision from the beginning to allow this. I'd suggest updating the docs to list $title as a required paramater but continue to leave it optional in the code and add a deprecated notice for developers.

**Comment by atanas-angelov-dev** [comment]
Thank you for your contributions however for simplicity and backwards compatibility reasons we've opted to use a different solution - more info in #26.

We may revisit specifying custom ids for containers in the future.

**Pull request closed without merging**
