### PR TITLE
Add Persian translation

### PR DESCRIPTION
**Pull request by wp-src**
Added Persian translation

### CODE REVIEW

**Comment by m1r0** [comment]
Thanks a lot @wp-src! :beers:

**Comment by m1r0** [comment]
Damn, forgot to add Persian in the changelog for version 1.5... Sorry about that @wp-src, will add it in the next version.

**Comment by wp-src** [comment]
No problem @m1r0 , 
What about a radio with images field. I think the framework needs such a field.
Thanks you and htmlburger team.

**Comment by m1r0** [comment]
@wp-src, well, we just got a new field! :yum: :beers:

**Pull request merged**
