### PR TITLE
Image Gallery Field

### PR DESCRIPTION
**Pull request by AlexBa**
Hi,
it took multiple hours of work, but I want to add an image gallery field.

This field is a child of the image field and allows to add, remove and sort multiple images (See the attachment).

Please check, if the code is working ;)

Regards,
Alexander Barton

screenshot 2016-09-20 19 12 10
screenshot 2016-09-20 19 12 27

### CODE REVIEW

**Comment by m1r0** [comment]
Hey @AlexBa, thanks for the great contribution! The field looks and works great!

We are going make a quick code review and merge it!

**Comment by AlexBa** [comment]
Sure, no problem. I work on two new features ("tag inputs" and "no duplicated complex fields") and try to make a pull request in the next 2-3 days. I need the those features for the next release ;)

**Comment by m1r0** [comment]
@AlexBa is it possible to rework the field a bit, so it works with all attachment types not just images? We decided that we need a more general `Gallery` field. If the developer wants to make an image gallery, he can use the `->set_type('image')` method. That way the field can cover more use cases.

**Comment by fgilio** [comment]
Wow I really like this.  Thanks @AlexBa 
Good idea with the further abstraction on the "gallery" type of field

**Comment by AlexBa** [comment]
@m1r0 Ok, I just need some days to do this ;)

**Comment by GasimGasimzada** [comment]
Wouldn't this make more sense if this field was a complex field called something like "Grid", which you can add anything -- text, image, color etc? So a syntax such as the following:

    Field::make( 'grid', 'photo-gallery' )
        ->add_fields( [
            Field::make( 'image', 'Photo' ),
        ] );

And the underlying data storage is the same as the one in Group field.

**Comment by schrapel** [comment]
@AlexBa @m1r0 what is the state of play of this PR? Do you need someone to make changes before a merge? I need to add a gallery field to the current project so to avoid creating my own field I'd like to help complete this one. Let me know what is outstanding.

**Comment by m1r0** [comment]
@schrapel if you really need this field at the moment I suggest just use the code from the pull request and the [carbon-field-template](https://github.com/htmlburger/carbon-field-template). The implementation should be pretty straight forward.

About the state of the pull request - we are not pushing fields/features at the moment, because there is a major JS rewrite in progress - we are migrating from Backbone to React.

When we make the core plugin more stable/maintainable, then its features time. :-)

**Comment by schrapel** [comment]
@m1r0 I've done it for anyone else that might want to use it https://github.com/schrapel/carbon-fields-image-gallery

I agree that there should be a general Gallery field but as long as the data structure doesn't change they should be replaceable. 

Do you agree with storing them as comma separated IDs?

**Comment by schrapel** [comment]
@AlexBa I'm also happy for you to maintain/own the repo since it's your work

**Comment by atanas-angelov-dev** [comment]
1.6 will be a maintenance release which aims at stability and full backwards compatibility so we will have to close feature pull requests aiming at 1.x.

Regardless, there is need for a gallery-like field which is why I've opened the new feature request issue #232

**Pull request closed without merging**
