### PR TITLE
Maps improvement: Autocomplete & search field update

### LINKED ISSUE #423: Add autocomplete to map field
Autocomplete in map field would be useful thing and relatively easily achieved.

When enqueueing google maps js api, url parameter `&libraries=places` needs to be added and some js like this

````
var autocomplete = new google.maps.places.Autocomplete(
	(document.getElementsByClassName("search-field")[1]),
 	{types: ['geocode']}
);
autocomplete.addListener('place_changed', function() {
	var place = autocomplete.getPlace();
	var latitude = place.geometry.location.lat();
	var longitude = place.geometry.location.lng();

       // update marker in map with this.map.marker.setPosition(place.geometry.location);
       // update map fields
});
````

### PR DESCRIPTION
**Pull request by iamntz**
Map field always felt a bit crippled: search field didn't really provide any feedback, moving pointer didn't provide any feedback either, selecting an exact point was feeling like an adventure.

So here we are, with some improvements:

1. Searching anything will also provide a nice autocomplete (by using [react places autocomplete](https://www.npmjs.com/package/react-places-autocomplete))
1. Moving pointer will update the search box
1. When configuring the field, you can make use of `->search_detail_level( 1 )` method in order to tweak the details provided by the search box (0 being the most detailed, 5 the most generic).

ezgif com-gif-maker

---

Obviously, this requires the right Google API permission (for places & geocoding).

---

This will close #423

I'm fairly new at the React game, so if I anything is not done „the react way”, please let me know :)

### CODE REVIEW

**Comment by ttamnedlog** [comment]
I apologize if this isn't the best place for this discussion, but how can I go ahead and integrate your pull request into my current personal project that's using Carbon Fields?

Unsure of the best/proper approach to integrating this, I just deleted `carbon-fields/` from `vendor/htmlburger/` and cloned your repo in its place. I then checked out the `maps-improvement` branch. Sadly, I saw no change at all. The map field continued to function the same way with no auto-complete or search updates.

Looking in my Google Console, I see that the Maps JavaScript API and occasionally the Geocoding API are getting requests, but Places API (or anything else) is not.

Are there additional steps necessary for this to work? Does something need to be compiled or installed? Any insight would be most appreciated.

**Comment by iamntz** [comment]
Yes, there is one more step: you need to run `npm install` then `npm run build` in the `carbon-fields` folder.

**Comment by ttamnedlog** [comment]
Thank you! It worked.

**Comment by iamntz** [comment]
Bumpy bump? @atanas-angelov-dev @deqngeorgiev could you guys please take a look at this? Thanks!

**Pull request closed without merging**
