### PR TITLE
Update carbon-fields-ru_RU.po

### PR DESCRIPTION
**Pull request by 9585999**

### CODE REVIEW

**Comment by atanas-angelov-dev** [comment]
Thank you for the contribution @9585999 !

I had to manually merge your changes in e6070adc70f15dcbd77516784befd71934acbf0c but Github hasn't recognized it as a merge so I'll close this pull.

Note that the updated Language file has a few new strings and we'll be very grateful if you're willing to help us out by making a new pull request with translations based on the `development` branch!

**Comment by 9585999** [comment]
@atanas-angelov-dev I understood correctly
Do I need to make a new translation?

**Comment by atanas-angelov-dev** [comment]
We have a few new strings that lack a translation in Russian so we would appreciate it if you can help us out (if you have the time, of course).

If you are up to it, you can checkout our `development` branch locally, update the `carbon-fields-ru_RU.po` file as necessary and submit a new pull request - just make sure you are on the tip of our `development` branch as it has a number of recent changes.

**Comment by 9585999** [comment]
@atanas-angelov-dev OK no problem

today, I will do it.

**Pull request closed without merging**
