### PR TITLE
Add carbon field number

### PR DESCRIPTION
**Pull request by pkostadinov-2create**
Adding the Number field.

By default the field will save integer value between 1 and 2147483647 (max int).

The field allows to change:
1. Min value - minimum value of the field, default 1
2. Max value - maximum value of the field, default 2147483647 
3. Step value - distance between 2 numbers, default 1. This can be used for non-integer numbers. For example the step can be setup to 0.1 for 1 decimal offset.

Available methods:
1. set_min
2. set_max
3. set_step

### CODE REVIEW

**Comment by pkostadinov-2create** [comment]
I have just updated the code, both PHP and JavaScript are now validating the values. This is implemented to allow the number field to work correcly for devices that does not support it like iOS and Android:

http://caniuse.com/#feat=input-number

**Comment by elvishp2006** [comment]
Is there any merge forecast for this feature? :smiley:

**Comment by Santana1053** [comment]
@pkostadinov-2create Will this cause any conflicts if the Carbon Fields plugin is installed on websites with your old number package installed?

**Comment by wkirby** [comment]
It would be great if this field type would support the `pattern` attribute.

**Comment by atanas-angelov-dev** [comment]
1.6 will be a maintenance release which aims at stability and full backwards compatibility so we will have to close feature pull requests aiming at 1.x.

In this case, the number field is already being prepared as a separate package for 2.0 and will be available on release.

**Pull request closed without merging**
