### PR TITLE
Static groups

### PR DESCRIPTION
**Pull request by AlexBa**
Hey there,
what do you think about static groups? Static groups are pre-rendered groups without any add or remove action. I'm working on an affiliate e-commerce project and if you define a product in my case, you now that there will be just 2 attribute groups for instance - not more or less.

I made this PR because I think there are some more developers who can benefit from this feature.

Here is an example (take a closer look on `set_static()`:

``` php
Container::make('post_meta', 'Custom Data')
             ->show_on_post_type('page')
             ->add_fields(array(
                 Field::make('complex', 'crb_job')
                      ->set_layout('tabbed')
                      ->set_static(true)
                      ->add_fields('driver', 'Driver', array(
                          Field::make('text', 'name'),
                          Field::make('text', 'drivers_license_id'),
                      ))
                     ->add_fields('teacher', 'Teacher', array(
                         Field::make('image', 'name'),
                         Field::make('image', 'years_of_experience'),
                     )),
             ));
```

screenshot 2016-10-18 12 48 23

screenshot 2016-10-18 13 00 59

Best regard,
Alexander Barton

### CODE REVIEW

**Comment by pkostadinov-2create** [comment]
This sounds just like tabs:
https://carbonfields.net/docs/containers-tabs/

Here is your code reworked with tabs:

```
Container::make('post_meta', 'Custom Data')
	->show_on_post_type('page')
	->add_tab('Driver', array(
		Field::make('text', 'crb_driver_name'),
		Field::make('text', 'crb_driver_license_id'),
	))
	->add_tab('Teacher', array(
		Field::make('image', 'crb_teacher_name'),
		Field::make('image', 'crb_teacher_experience'),
	))
));
```

Tabs also work on different containers, like theme_options, where there is even a deep linking available.

**Comment by m1r0** [comment]
@AlexBa It's a really cool idea to make the complex field pre-render the groups and make them static if needed. It would be handy if we can separate the pre-rendering and the locking part. What do you think about the following:

```
Container::make('post_meta', 'Custom Data')
	->show_on_post_type('page')
	->add_fields(array(
		 Field::make('complex', 'crb_job')
			->set_layout('tabbed')
			->pre_render( ['driver', 'teacher'] ) // maybe allow ['driver' => 2, 'teacher' => 3] for rendering multiple groups of the same type
			->lock() // disables add/remove/sort/duplicate
			->add_fields('driver', array(
				Field::make('text', 'name'),
				Field::make('text', 'drivers_license_id'),
			))
			->add_fields('teacher', 'Teacher', array(
				Field::make('image', 'name'),
				Field::make('image', 'years_of_experience'),
			)),
	 ));
```

Here is an another use case using `set_min`:

```
Container::make('post_meta', 'Custom Data')
	->show_on_post_type('page')
	->add_fields(array(
		 Field::make('complex', 'crb_job')
			->set_layout('tabbed')
			->set_min( 2 )
			->pre_render( 2 )
			->set_required( true )
			->add_fields(array(
				Field::make('text', 'name'),
				Field::make('text', 'drivers_license_id'),
			))
	 ));
```

P.S. Maybe we need to think of a better method name for the `pre_render` method.

**Comment by AlexBa** [comment]
@pkostadinov-2create Yeah, it's similar to tabs. The only problem with tabs is, that you have to give the related fields a "full name" like "crb_driver_name" on build-time and if you want to fetch the fields, you have to build a template like "crb_driver_%s" to fetch all fields. 

But imagine a scenario, where you just know the group name like "crb_driver" and want to easily fetch the fields with a good performance or you want to add the possiblity for other developers to hook custom fields. That's pretty much what complex fields with groups are doing. 

I just tried to solve the problem, where a developer knows, that there are a limited amount of groups - not more and not less. I have thought days about another good solution with carbon fields, but there are none yet.

**Comment by AlexBa** [comment]
@m1r0 I like the naming and the idea of ```pre_render( ['driver', 'teacher'] )```. I will upgrade the code this week.

**Comment by atanas-angelov-dev** [comment]
1.6 will be a maintenance release which aims at stability and full backwards compatibility so we will have to close feature pull requests aiming at 1.x.

I've opened a new feature request issue #234 for this functionality aimed for a 2.x release.

**Pull request closed without merging**
